### ISSUE TITLE
Building without mercurial installed fails

### ISSUE THREAD

**Issue by vrischmann** [mozilla-services/heka-build#10]
Not sure if the script can use the downloaded Mercurial in the virtualenv since this is in go build script somewhere.
Tested on Debian Wheezy.

```
cd build/go/src && \
    ./all.bash
# Building C bootstrap tool.
cmd/dist
go tool dist: FAILED: hg identify -b
./make.bash: line 116: hg: command not found
make: *** [/root/heka-build/bin/go] Error 127
```

**Comment by mblair** [comment]
Looks like this may have been fixed with 82af7d6071cc2a6f11e6ec2db5ccd9abb26abb29.

**Comment by rafrombrc** [comment]
Yes, this should be the case. Can you pull the latest heka-build code, @vrischmann, and let us know whether or not that helps?

**Comment by vrischmann** [comment]
So I just pulled the latest revision and it's still not working. The error is exactly the same.

**Comment by rafrombrc** [comment]
Whoops, sorry about that. I made some changes to make sure that the mercurial that we pull down is always on the path when we need it. I can now successfully build from a fresh heka-build checkout on a machine w/o a pre-existing `hg` available on the path. Would love if you'd test and confirm. Thanks!

**Comment by rafrombrc** [comment]
Mercurial is now specified as a dependency rather than something provided by the build (see http://hekad.readthedocs.org/en/latest/installing.html).
